import localFont from "next/font/local";
import "./globals.css";
import LayoutWrapper from "@/components/LayoutWrapper";

const monaSansCondensed = localFont({
  src: [
    {
      path: "../public/font/monalight.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/font/mona.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-mona-sans",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`${monaSansCondensed.variable} antialiased`}
      >
        <main>
          <LayoutWrapper>{children}</LayoutWrapper>
        </main>
      </body>
    </html>
  );
}
